name: flutter_gradient_text
description: "A Flutter plugin project to provide gradient color applied text"
version: 1.0.0
homepage: https://github.com/trdevendran/flutter_gradient_text.git

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
